# Generated by Django 3.0.8 on 2020-08-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.CharField(default='Individual', max_length=255),
        ),
    ]
